// Auto-generated Google Business Profile Local SEO Location Configuration
export const gbpLocation = {
  storeName: "Green Deal Cannabis",
  domain: "www.greendealcannabis.com",
  city: "York",
  province: "ON",
  country: "CA",
  slug: "weed-dispensary-york",
  address: "1820 Jane St, York, ON M9N 2T3",
  streetAddress: "1820 Jane St",
  postalCode: "M9N 2T3",
  phone: "(942) 288-4633",
  phoneIntl: "+19422884633",
  neighborhood: "York / Weston",
  nearbyAreas: ["York", "Eglinton West", "Weston", "Keelesdale", "Mount Dennis", "Caledonia", "Rogers Road", "TTC"],
  products: [
    "Flower",
    "Pre-rolls",
    "Edibles",
    "THC vapes",
    "Concentrates",
    "Shatter",
    "CBD oils",
    "Accessories"
  ],
  menuUrl: "/",
  directionsUrl: "",
  mapEmbedUrl: "",
  latitude: "43.7003889",
  longitude: "-79.5042654",
  hours: ["Open Daily 10AM - 2AM"],
  seoTitle: "Green Deal Cannabis | Weed Dispensary in York",
  metaDescription: "Green Deal Cannabis is a local weed dispensary in York offering flower, pre-rolls, edibles, vapes, concentrates, CBD, and service for adults 19+.",
  localLandmarks: ["York", "Eglinton West", "Weston"],
  introVariant: "Green Deal Cannabis is located at 1820 Jane St in York. Adults 19+ can browse cannabis flower, pre-rolls, edibles, THC vapes, concentrates, CBD products, and accessories. Visit the store page and menu categories for current details near York and Weston.",
  neighborhoodDescription: "Located in the vibrant York / Weston district, our cannabis store fits right into this active and historic community, surrounded by local retail shops and convenient transit links.",
  parkingNote: "Designated customer parking is available on-site",
  transitNote: "Accessible by local TTC bus routes around Jane Street and Eglinton Avenue.",
  sectionTitle: "Serving Customers Near York and Eglinton West"
};
